language: node_js
node_js:
  - '12.14.1'

branches:
  only:
    - master

addons:
  chrome: stable

install:
  sh scripts/install.sh

script:
  sh scripts/build.sh

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: development

notifications:
  email: false

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules
