dist: trusty
language: node_js
node_js:
  - '12.14.1'

branches:
  only:
    - development

addons:
  chrome: stable

script:
  sh build.sh

notifications:
  email: false

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules
