dist: trusty
language: node_js
node_js:
  - '12.14.1'

branches:
  only:
    - development

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  cd backend && npm install
  cd ../frontend && npm install

script:
  cd frontend && npm run test-single

notifications:
  email: false

#branches:
#  only:
#    - master

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules
