dist: trusty
language: node_js
node_js:
  - '12.14.1'

branches:
  only:
    - development

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

script:
  cd backend && npm install
  cd ../frontend && npm install
  npm run test-single

notifications:
  email: false

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules
