dist: trusty
language: node_js
node_js:
  - '12.14.1'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  backend/npm install
  frontend/npm install

script:
  frontend/npm run test-single
